# Generated by Django 3.0 on 2020-06-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_user', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('complaintDate', models.DateField(auto_now=True)),
                ('assigned_user', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=30)),
                ('complaint_status', models.CharField(max_length=30)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
